# Generated by Django 5.2.8 on 2025-11-13 06:35

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='mode',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=20),
        ),
    ]
