# Generated by Django 5.2.7 on 2025-11-05 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='title',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='uploaded_at',
        ),
    ]
