# Generated by Django 5.2.8 on 2025-11-13 08:24

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='gallery/'),
        ),
    ]
