# Generated by Django 5.2.8 on 2025-11-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='team_photos/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('qualification', models.CharField(max_length=200)),
            ],
        ),
    ]
