# Generated by Django 5.2.8 on 2025-11-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team_photos/')),
                ('name', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=200)),
                ('batches', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('date_of_joining', models.DateField()),
            ],
        ),
    ]
