# Generated by Django 5.2.8 on 2025-11-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='date_of_joining',
            field=models.DateField(auto_now_add=True),
        ),
    ]
