# Generated by Django 5.2.8 on 2025-11-14 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_teammember_photo'),
        ('accounts', '0010_image_title'),
    ]

    operations = [
    ]
