# Generated by Django 5.2.8 on 2025-11-10 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punch_in_time', models.DateTimeField(auto_now_add=True)),
                ('punch_out_time', models.DateTimeField(blank=True, null=True)),
                ('punch_in_selfie', models.ImageField(help_text='Selfie taken at the time of punch-in.', upload_to='attendance_selfies/%Y/%m/%d/')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-punch_in_time'],
            },
        ),
    ]
