# Generated by Django 5.2.8 on 2025-11-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='working_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
