# Generated by Django 5.2.8 on 2025-11-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_leaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='duration_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
