# Generated by Django 5.2.8 on 2025-11-13 08:34

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_leaverequest_duration_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='punch_in_selfie',
            field=models.ImageField(default='', help_text='Selfie taken at the time of punch-in.', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='attendance_selfies/%Y/%m/%d/'),
        ),
    ]
